# SPDX-License-Identifier: GPL-2.0
KBUILD_EXTRA_SYMBOLS += $(src)/../safety_mem/Module.symvers
obj-m += mutex_threads.o
obj-m += rogue_thread.o

ccflags-y := -Wall -Wextra -Werror -Wno-unused-parameter
